<#
.SYNOPSIS
Generates a VyOS config.boot file from a router-definition JSON file.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$DefinitionFile,
    [string]$OutputPath = (Join-Path $PSScriptRoot 'vyos-router.config.boot')
)

$ErrorActionPreference = 'Stop'
if (-not (Test-Path -LiteralPath $DefinitionFile -PathType Leaf)) {
    throw "Router definition file not found: $DefinitionFile"
}

$definition = Get-Content -LiteralPath $DefinitionFile -Raw | ConvertFrom-Json
function Require-Value($Object, [string]$Name) {
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property -or [string]::IsNullOrWhiteSpace("$($property.Value)")) {
        throw "Required setting is missing: $Name"
    }
    return "$($property.Value)"
}
function Optional-Value($Object, [string]$Name) {
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    return $property.Value
}
function Assert-IPv4Cidr([string]$Value, [string]$Setting) {
    if ($Value -notmatch '^\d{1,3}(\.\d{1,3}){3}/([0-9]|[12][0-9]|3[0-2])$') {
        throw "$Setting must be an IPv4 CIDR value, for example 192.168.10.0/24."
    }
    [void][System.Net.IPAddress]::Parse(($Value -split '/')[0])
}
function Assert-IPv4([string]$Value, [string]$Setting) {
    try {
        $address = [System.Net.IPAddress]::Parse($Value)
        if ($address.AddressFamily -ne [System.Net.Sockets.AddressFamily]::InterNetwork) { throw }
    }
    catch { throw "$Setting must be an IPv4 address." }
}
function VyOS-Quote([string]$Value) {
    if ($Value -match '[\r\n\x00]') { throw 'Configuration values must not contain newlines or NUL characters.' }
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}
function Assert-Interface([string]$Value, [string]$Setting) {
    if ($Value -notmatch '^[a-z]+[0-9]+$') { throw "$Setting must look like eth0 or eth1." }
}

$hostname = Require-Value $definition 'hostname'
$admin = Optional-Value $definition 'admin'
if ($null -eq $admin) { throw 'Required setting is missing: admin.' }
$adminUser = Require-Value $admin 'username'
$passwordHash = Require-Value $admin 'encryptedPassword'
$wan = Optional-Value $definition 'wan'
if ($null -eq $wan) { throw 'Required setting is missing: wan.' }
$wanParent = Require-Value $wan 'parentInterface'
Assert-Interface $wanParent 'wan.parentInterface'
$wanMode = Require-Value $wan 'addressMode'
if ($wanMode -notin @('dhcp', 'static')) { throw 'wan.addressMode must be dhcp or static.' }
$wanVlan = Optional-Value $wan 'vlanId'
if ($null -ne $wanVlan -and ([int]$wanVlan -lt 1 -or [int]$wanVlan -gt 4094)) { throw 'wan.vlanId must be 1 through 4094.' }
$wanAddress = Optional-Value $wan 'address'
$wanGateway = Optional-Value $wan 'gateway'
if ($wanMode -eq 'static') {
    Assert-IPv4Cidr "$wanAddress" 'wan.address'
    Assert-IPv4 "$wanGateway" 'wan.gateway'
}

$lanList = @(Optional-Value $definition 'lans')
if ($lanList.Count -eq 0 -or $null -eq $lanList[0]) { throw 'At least one LAN definition is required.' }
$interfaces = [System.Collections.Generic.List[object]]::new()
$interfaces.Add([pscustomobject]@{ Parent = $wanParent; Vlan = $wanVlan; Address = if ($wanMode -eq 'dhcp') { 'dhcp' } else { "$wanAddress" } })
$lanRecords = [System.Collections.Generic.List[object]]::new()
foreach ($lan in $lanList) {
    $lanName = Require-Value $lan 'name'
    $parent = Require-Value $lan 'parentInterface'
    Assert-Interface $parent "LAN $lanName parentInterface"
    $vlan = Optional-Value $lan 'vlanId'
    if ($null -ne $vlan -and ([int]$vlan -lt 1 -or [int]$vlan -gt 4094)) { throw "LAN $lanName vlanId must be 1 through 4094." }
    $subnet = Require-Value $lan 'subnet'
    $gateway = Require-Value $lan 'gateway'
    Assert-IPv4Cidr $subnet "LAN $lanName subnet"
    Assert-IPv4 $gateway "LAN $lanName gateway"
    $interfaces.Add([pscustomobject]@{ Parent = $parent; Vlan = $vlan; Address = $gateway + '/' + (($subnet -split '/')[1]) })
    $lanRecords.Add([pscustomobject]@{ Name = $lanName; Subnet = $subnet; Gateway = $gateway; Dhcp = (Optional-Value $lan 'dhcp') })
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('/* Generated by New-VyOSRouterConfig.ps1. */')
$lines.Add('interfaces {')
foreach ($parentGroup in ($interfaces | Group-Object Parent)) {
    $lines.Add("    ethernet $($parentGroup.Name) {")
    foreach ($entry in $parentGroup.Group | Where-Object { $null -eq $_.Vlan }) { $lines.Add("        address $(VyOS-Quote $entry.Address)") }
    foreach ($entry in $parentGroup.Group | Where-Object { $null -ne $_.Vlan }) {
        $lines.Add("        vif $($entry.Vlan) {")
        $lines.Add("            address $(VyOS-Quote $entry.Address)")
        $lines.Add('        }')
    }
    $lines.Add('    }')
}
$lines.Add('}')

$enableNat = Optional-Value $definition 'enableNat'
if ($null -eq $enableNat) { $enableNat = $true }
$wanLogical = if ($null -eq $wanVlan) { $wanParent } else { "$wanParent.$wanVlan" }
if ([bool]$enableNat) {
    $lines.Add('nat {'); $lines.Add('    source {')
    $rule = 100
    foreach ($lan in $lanRecords) {
        $lines.Add("        rule $rule {"); $lines.Add('            outbound-interface {'); $lines.Add("                name $(VyOS-Quote $wanLogical)"); $lines.Add('            }')
        $lines.Add('            source {'); $lines.Add("                address $(VyOS-Quote $lan.Subnet)"); $lines.Add('            }')
        $lines.Add('            translation {'); $lines.Add('                address "masquerade"'); $lines.Add('            }'); $lines.Add('        }')
        $rule += 10
    }
    $lines.Add('    }'); $lines.Add('}')
}

$lines.Add('service {'); $lines.Add('    ssh {'); $lines.Add('        port "22"'); $lines.Add('    }')
$dhcpLans = @($lanRecords | Where-Object { $null -ne $_.Dhcp -and [bool](Optional-Value $_.Dhcp 'enabled') })
if ($dhcpLans.Count -gt 0) { $lines.Add('    dhcp-server {') }
$subnetId = 1
foreach ($lan in $dhcpLans) {
    $dhcp = $lan.Dhcp
    $start = Require-Value $dhcp 'start'; $stop = Require-Value $dhcp 'stop'
    Assert-IPv4 $start "DHCP $($lan.Name) start"; Assert-IPv4 $stop "DHCP $($lan.Name) stop"
    $lines.Add("        shared-network-name $(VyOS-Quote $lan.Name) {"); $lines.Add("            subnet $($lan.Subnet) {")
    $lines.Add("                subnet-id $subnetId")
    $subnetId++
    $lines.Add('                option {')
    $lines.Add("                    default-router $(VyOS-Quote $lan.Gateway)")
    $dnsServers = @(Optional-Value $dhcp 'dnsServers'); if ($dnsServers.Count -eq 0 -or $null -eq $dnsServers[0]) { $dnsServers = @($lan.Gateway) }
    foreach ($dns in $dnsServers) { Assert-IPv4 "$dns" "DHCP $($lan.Name) dnsServers"; $lines.Add("                    name-server $(VyOS-Quote "$dns")") }
    $lines.Add('                }')
    $lines.Add('                range 0 {'); $lines.Add("                    start $(VyOS-Quote $start)"); $lines.Add("                    stop $(VyOS-Quote $stop)"); $lines.Add('                }')
    $lines.Add('            }'); $lines.Add('        }')
}
if ($dhcpLans.Count -gt 0) { $lines.Add('    }') }
$lines.Add('}')

$bgp = Optional-Value $definition 'bgp'
if ($wanMode -eq 'static' -or $null -ne $bgp) { $lines.Add('protocols {') }
if ($wanMode -eq 'static') {
    $lines.Add('    static {'); $lines.Add('        route 0.0.0.0/0 {')
    $lines.Add("            next-hop $wanGateway {"); $lines.Add('            }')
    $lines.Add('        }'); $lines.Add('    }')
}
if ($null -ne $bgp) {
    $localAs = Require-Value $bgp 'localAs'; $routerId = Require-Value $bgp 'routerId'; Assert-IPv4 $routerId 'bgp.routerId'
    $lines.Add('    bgp {'); $lines.Add("        system-as $(VyOS-Quote $localAs)")
    $lines.Add('        parameters {'); $lines.Add("            router-id $(VyOS-Quote $routerId)"); $lines.Add('        }')
    $networks = @(Optional-Value $bgp 'advertiseNetworks')
    if ($networks.Count -gt 0 -and $null -ne $networks[0]) { $lines.Add('        address-family {'); $lines.Add('            ipv4-unicast {'); foreach ($network in $networks) { Assert-IPv4Cidr "$network" 'bgp.advertiseNetworks'; $lines.Add("                network $(VyOS-Quote "$network")") }; $lines.Add('            }'); $lines.Add('        }') }
    foreach ($neighbor in @(Optional-Value $bgp 'neighbors')) {
        if ($null -eq $neighbor) { continue }
        $peer = Require-Value $neighbor 'address'; $remoteAs = Require-Value $neighbor 'remoteAs'; Assert-IPv4 $peer 'BGP neighbor address'
        $lines.Add("        neighbor $(VyOS-Quote $peer) {"); $lines.Add('            address-family {'); $lines.Add('                ipv4-unicast {'); $lines.Add('                }'); $lines.Add('            }'); $lines.Add("            remote-as $(VyOS-Quote $remoteAs)")
        $description = Optional-Value $neighbor 'description'; if ($description) { $lines.Add("            description $(VyOS-Quote "$description")") }
        $updateSource = Optional-Value $neighbor 'updateSource'; if ($updateSource) { $lines.Add("            update-source $(VyOS-Quote "$updateSource")") }
        $multiHop = Optional-Value $neighbor 'ebgpMultihop'; if ($multiHop) { $lines.Add("            ebgp-multihop $(VyOS-Quote "$multiHop")") }
        $lines.Add('        }')
    }
    $lines.Add('    }')
}
if ($wanMode -eq 'static' -or $null -ne $bgp) { $lines.Add('}') }

$lines.Add('system {'); $lines.Add("    host-name $(VyOS-Quote $hostname)"); $lines.Add('    login {'); $lines.Add("        user $(VyOS-Quote $adminUser) {"); $lines.Add('            authentication {'); $lines.Add("                encrypted-password $(VyOS-Quote $passwordHash)"); $lines.Add('            }'); $lines.Add('        }'); $lines.Add('    }'); $lines.Add('}')

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) { [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null }
$lines | Set-Content -LiteralPath $OutputPath -Encoding utf8
Write-Host "Generated VyOS config.boot: $((Resolve-Path -LiteralPath $OutputPath).Path)"
